In [1]:
import os
os.getcwd()


'c:\\Users\\kevin\\OneDrive\\Desktop\\GitHub\\Machine_Learning_ZOOM'

In [2]:
import numpy as np

In [3]:
np

<module 'numpy' from 'c:\\Users\\kevin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\numpy\\__init__.py'>

One Dimension Array

In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [7]:
a = np.array([1,2,3,5,7,12])

In [8]:
a[2]

3

In [9]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [10]:
# multi dimension array

In [11]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [12]:
n = np.array([[10 ,3],[100 ,3]])

In [13]:
n[0,0]

10

In [14]:
n[0,1]

3

In [15]:
n[1,0]

100

In [16]:
n[1]

array([100,   3])

In [17]:
n[:]

array([[ 10,   3],
       [100,   3]])

In [18]:
np. random.seed(0)
np. random.rand(1,1)

array([[0.5488135]])

In [19]:
import pandas as pd


In [20]:
pd.__version__

'1.5.3'

In [21]:
np. random.seed(2)
np. random.randint(low=0,high=100, size=(5, 2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

If you need floating-point random values (e.g., for machine learning initialization), use rand().
If you need integer random values (e.g., for class labels or IDs), use randint().

In [22]:

# Element-wise operation 
a = np.arange(5)
a



array([0, 1, 2, 3, 4])

In [23]:
a*100

array([  0, 100, 200, 300, 400])

In [24]:
#comaprison operator

In [25]:
u  = np.array([2, 4, 5,6])
v  = np.array([1, 0, 0,2])





In [26]:
def vector_vector_multiplication(u,v):
     assert u.shape[0] == v.shape[0]
     n = u.shape[0]
     results = 0
     for i in range(n):
         results = results + u[i]*v[i]
     return results
    

In [27]:
vector_vector_multiplication(u,v)

14

In [28]:
u.dot(v)

14

In [31]:
def matrix_vector_ultiplication(u,v):
     assert u.shape[1] == v.shape[0]
     num_rows = u.shape[1]
     results = np.zeros(num_rows)
     for i in range(num_rows):
         resultS[i] = u*v
     return results

In [32]:
#1.9 pandas for manipulating tablular data 
pd

<module 'pandas' from 'c:\\Users\\kevin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\__init__.py'>

In [ ]:
data frame

In [35]:
data = [
    ['Nissan', 'Stanza', 1991, 138, 4, 'MANUAL', 'sedan', 2000],
    ['Hyundai', 'Sonata', 2017, None, 4, 'AUTOMATIC', 'Sedan', 27150],
    ['Lotus', 'Elise', 2010, 218, 4, 'MANUAL', 'convertible', 54990],
    ['GMC', 'Acadia',  2017, 194, 4, 'AUTOMATIC', '4dr SUV', 34450],
    ['Nissan', 'Frontier', 2017, 261, 6, 'MANUAL', 'Pickup', 32340],
]

columns = [
    'Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
    'Transmission Type', 'Vehicle_Style', 'MSRP'
]

In [37]:
df = pd.DataFrame(data,columns=columns)

In [38]:
print (df)

      Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340  


In [39]:
data = [
    {
        "Make": "Nissan",
        "Model": "Stanza",
        "Year": 1991,
        "Engine HP": 138.0,
        "Engine Cylinders": 4,
        "Transmission Type": "MANUAL",
        "Vehicle_Style": "sedan",
        "MSRP": 2000
    },
    {
        "Make": "Hyundai",
        "Model": "Sonata",
        "Year": 2017,
        "Engine HP": None,
        "Engine Cylinders": 4,
        "Transmission Type": "AUTOMATIC",
        "Vehicle_Style": "Sedan",
        "MSRP": 27150
    },
    {
        "Make": "Lotus",
        "Model": "Elise",
        "Year": 2010,
        "Engine HP": 218.0,
        "Engine Cylinders": 4,
        "Transmission Type": "MANUAL",
        "Vehicle_Style": "convertible",
        "MSRP": 54990
    },
    {
        "Make": "GMC",
        "Model": "Acadia",
        "Year": 2017,
        "Engine HP": 194.0,
        "Engine Cylinders": 4,
        "Transmission Type": "AUTOMATIC",
        "Vehicle_Style": "4dr SUV",
        "MSRP": 34450
    },
    {
        "Make": "Nissan",
        "Model": "Frontier",
        "Year": 2017,
        "Engine HP": 261.0,
        "Engine Cylinders": 6,
        "Transmission Type": "MANUAL",
        "Vehicle_Style": "Pickup",
        "MSRP": 32340
    }
]

In [46]:
df = pd.DataFrame(data)
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

In [48]:
df = df.head(n = 2)
df

Make   Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan  Stanza  1991      138.0                 4            MANUAL   
1  Hyundai  Sonata  2017        NaN                 4         AUTOMATIC   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150

In [50]:
#series
#that is how columns in data frame called 

In [53]:
df=df.head(n=5)
df.Make

0     Nissan
1    Hyundai
Name: Make, dtype: object

In [58]:
df = pd.DataFrame(data)
df['Engine HP']

0    138.0
1      NaN
2    218.0
3    194.0
4    261.0
Name: Engine HP, dtype: float64

In [57]:
df[['Make','Model','MSRP']]

Make   Model   MSRP
0   Nissan  Stanza   2000
1  Hyundai  Sonata  27150

In [63]:
df['id'] =[1,2,3,4,5]

In [72]:
df['id'] = [10, 20, 30, 40, 50]
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  id  
0         sedan   2000  10  
1         Sedan  27150  20  
2   convertible  54990  30  
3       4dr SUV  34450  40  
4        Pickup  32340  50

In [73]:
del df['id']


In [74]:
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

In [75]:
#index*
#access the elemnts of dataframe 

In [76]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [78]:
df.Make.index

RangeIndex(start=0, stop=5, step=1)

In [80]:
df.index = ['a', 'b', 'c', 'd', 'e']
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
a   Nissan    Stanza  1991      138.0                 4            MANUAL   
b  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
c    Lotus     Elise  2010      218.0                 4            MANUAL   
d      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
e   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
a         sedan   2000  
b         Sedan  27150  
c   convertible  54990  
d       4dr SUV  34450  
e        Pickup  32340

In [81]:
df.iloc[[1, 2, 4]]

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
b  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
c    Lotus     Elise  2010      218.0                 4            MANUAL   
e   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
b         Sedan  27150  
c   convertible  54990  
e        Pickup  32340

In [83]:
df = df.reset_index(drop=True)
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

In [85]:
df['Year'] >= 2015

0    False
1     True
2    False
3     True
4     True
Name: Year, dtype: bool

In [87]:

  df[df['Make'] == 'Nissan']

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0  Nissan    Stanza  1991      138.0                 4            MANUAL   
4  Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
4        Pickup  32340

In [88]:
'machine learning zoomcamp'.replace(' ', '_')

'machine_learning_zoomcamp'

In [89]:
df['Vehicle_Style'].str.lower()

0          sedan
1          sedan
2    convertible
3        4dr suv
4         pickup
Name: Vehicle_Style, dtype: object

In [92]:
df.describe().round(10)

Year  Engine HP  Engine Cylinders          MSRP
count     5.000000    4.00000          5.000000      5.000000
mean   2010.400000  202.75000          4.400000  30186.000000
std      11.260551   51.29896          0.894427  18985.044904
min    1991.000000  138.00000          4.000000   2000.000000
25%    2010.000000  180.00000          4.000000  27150.000000
50%    2017.000000  206.00000          4.000000  32340.000000
75%    2017.000000  228.75000          4.000000  34450.000000
max    2017.000000  261.00000          6.000000  54990.000000

In [93]:
df.nunique()

Make                 4
Model                5
Year                 3
Engine HP            4
Engine Cylinders     2
Transmission Type    2
Vehicle_Style        5
MSRP                 5
dtype: int64

In [94]:
df.isnull().sum()

Make                 0
Model                0
Year                 0
Engine HP            1
Engine Cylinders     0
Transmission Type    0
Vehicle_Style        0
MSRP                 0
dtype: int64

In [95]:
df.isnull()

Make  Model   Year  Engine HP  Engine Cylinders  Transmission Type  \
0  False  False  False      False             False              False   
1  False  False  False       True             False              False   
2  False  False  False      False             False              False   
3  False  False  False      False             False              False   
4  False  False  False      False             False              False   

   Vehicle_Style   MSRP  
0          False  False  
1          False  False  
2          False  False  
3          False  False  
4          False  False

In [96]:
df.groupby('Transmission Type').MSRP.max()

Transmission Type
AUTOMATIC    34450
MANUAL       54990
Name: MSRP, dtype: int64

In [98]:
df.groupby('Transmission Type').MSRP.mean()

Transmission Type
AUTOMATIC    30800.000000
MANUAL       29776.666667
Name: MSRP, dtype: float64