In [7]:
import os
os.getcwd()


'C:\\Users\\kevin\\anaconda3\\envs\\ml-zoomcamp'

In [8]:
import numpy as np

In [9]:
np

<module 'numpy' from 'C:\\Users\\kevin\\anaconda3\\Lib\\site-packages\\numpy\\__init__.py'>

One Dimension Array

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [14]:
a = np.array([1,2,3,5,7,12])

In [15]:
a[2]

3

In [16]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [17]:
# multi dimension array

In [18]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [19]:
n = np.array([[10 ,3],[100 ,3]])

In [20]:
n[0,0]

10

In [21]:
n[0,1]

3

In [22]:
n[1,0]

100

In [23]:
n[1]

array([100,   3])

In [24]:
n[:]

array([[ 10,   3],
       [100,   3]])

In [25]:
np. random.seed(0)
np. random.rand(1,1)

array([[0.5488135]])

In [26]:
import pandas as pd


In [27]:
pd.__version__

'2.2.2'

In [129]:
np. random.seed(2)
np. random.randint(low=0,high=100, size=(5, 2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

If you need floating-point random values (e.g., for machine learning initialization), use rand().
If you need integer random values (e.g., for class labels or IDs), use randint().

In [140]:

# Element-wise operation 
a = np.arange(5)
a



array([0, 1, 2, 3, 4])

In [142]:
a*100

array([  0, 100, 200, 300, 400])

In [ ]:
#comaprison operator

In [145]:
u  = np.array([2, 4, 5,6])
v  = np.array([1, 0, 0,2])





In [121]:
def vector_vector_multiplication(u,v):
     assert u.shape[0] == v.shape[0]
     n = u.shape[0]
     results = 0
     for i in range(n):
         results = results + u[i]*v[i]
     return results
    

In [125]:
vector_vector_multiplication(u,v)

14

In [127]:
u.dot(v)

14

In [ ]:
def matrix_vector_ultiplication(u,v):
     assert u.shape[1] == v.shape[0]
     num_rows = u.shape[1]
     results = np.zeros(num_rows)
     for i in range(num_rows):
         resultS[i] = 
     return results